# Generated by Django 5.1.4 on 2024-12-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='About Description')),
                ('paragraph1', models.TextField(verbose_name='Paragraph 1')),
                ('bullet1', models.TextField(verbose_name='Bullet Point 1')),
                ('bullet2', models.TextField(verbose_name='Bullet Point 2')),
                ('bullet3', models.TextField(verbose_name='Bullet Point 3')),
                ('paragraph2', models.TextField(verbose_name='Paragraph 2')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('about_image', models.ImageField(upload_to='about/', verbose_name='About Image')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='BookADateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(max_length=100, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Customer Phone Number')),
                ('event_date', models.DateField(verbose_name='Date of Event')),
                ('event_time', models.TimeField(verbose_name='Time of Event')),
                ('num_people', models.IntegerField(verbose_name='Number of People')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='BookADateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_a_date/', verbose_name='Card Image')),
            ],
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours', models.TextField(verbose_name='Opening Hours')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='EventsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('picture', models.ImageField(upload_to='events/', verbose_name='Event Picture')),
                ('description', models.TextField(verbose_name='Event Description')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, verbose_name='Headline')),
                ('title_text', models.CharField(max_length=100, verbose_name='Title Text')),
                ('description', models.TextField(verbose_name='Description')),
                ('cta_button_text', models.CharField(max_length=100, verbose_name='CTA Button Text')),
                ('watch_video_button_link', models.URLField(verbose_name='Watch Video Button Link')),
                ('dish_image', models.ImageField(upload_to='home/', verbose_name='Dish Image')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph1', models.TextField(verbose_name='Paragraph 1')),
                ('card1_title', models.CharField(max_length=100, verbose_name='Card 1 Title')),
                ('card1_paragraph', models.TextField(verbose_name='Card 1 Paragraph')),
                ('card2_title', models.CharField(max_length=100, verbose_name='Card 2 Title')),
                ('card2_paragraph', models.TextField(verbose_name='Card 2 Paragraph')),
                ('card3_title', models.CharField(max_length=100, verbose_name='Card 3 Title')),
                ('card3_paragraph', models.TextField(verbose_name='Card 3 Paragraph')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dish Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('image', models.ImageField(upload_to='menu/', verbose_name='Image')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='baseApp.menucategory', verbose_name='Category')),
            ],
        ),
    ]
