# Generated by Django 5.1.4 on 2024-12-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='about_image',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='about_image1',
            field=models.ImageField(default='default.jpg1', upload_to='about/', verbose_name='About Image 1'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='about_image2',
            field=models.ImageField(default='default.jpg2', upload_to='about/', verbose_name='About Image 2'),
        ),
    ]
