# Generated by Django 5.1.4 on 2024-12-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_remove_aboutsection_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventssection',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Event Slug'),
        ),
    ]
