# Generated by Django 5.1.4 on 2024-12-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_eventssection_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='websiteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, verbose_name='Headline')),
                ('title_logo', models.ImageField(upload_to='favicon/', verbose_name='title icon')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Business logo')),
            ],
        ),
    ]
