# Generated by Django 5.1.4 on 2024-12-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_websitedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='eventssection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='whychoosesection',
            name='slug',
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
