# Generated by Django 5.1.4 on 2024-12-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_remove_aboutsection_slug_remove_eventssection_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitedetail',
            name='slug',
        ),
    ]
