# Generated by Django 5.1.4 on 2024-12-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_remove_websitedetail_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Meta Description')),
                ('keywords', models.TextField(verbose_name='Meta Keywords')),
                ('author', models.CharField(max_length=100, verbose_name='Author/Business Name')),
            ],
        ),
    ]
