# Generated by Django 5.1.4 on 2024-12-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image1_description',
            field=models.CharField(default='default', max_length=400, verbose_name='Image 1 description'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image2_description',
            field=models.CharField(default='default', max_length=400, verbose_name='Image 1 description'),
        ),
        migrations.AddField(
            model_name='bookadatesection',
            name='image_description',
            field=models.CharField(default='default', max_length=400, verbose_name='BookADate Section Image Description'),
        ),
        migrations.AddField(
            model_name='eventssection',
            name='image_description',
            field=models.CharField(default='default', max_length=400, verbose_name='Event Image description'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='image_description',
            field=models.CharField(blank=True, max_length=400, verbose_name='dish image description'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_description',
            field=models.CharField(blank=True, max_length=400, verbose_name='item image description'),
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='logo_description',
            field=models.CharField(blank=True, max_length=400, verbose_name='logo description'),
        ),
    ]
