# Generated by Django 5.1.4 on 2024-12-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_alter_bookadateform_num_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitedetail',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='websitedetail',
            name='logo_description',
        ),
    ]
