# Generated by Django 5.1.4 on 2025-01-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_remove_websitedetail_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='about_image2',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='image2_description',
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='about_image1',
            field=models.ImageField(default='default.jpg1', upload_to='media/about/', verbose_name='About Image 1'),
        ),
        migrations.AlterField(
            model_name='bookadatesection',
            name='image',
            field=models.ImageField(upload_to='media/book_a_date/', verbose_name='Card Image'),
        ),
        migrations.AlterField(
            model_name='eventssection',
            name='picture',
            field=models.ImageField(upload_to='media/events/', verbose_name='Event Picture'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='dish_image',
            field=models.ImageField(upload_to='media/home/', verbose_name='Dish Image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='media/menu/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='websitedetail',
            name='title_logo',
            field=models.ImageField(upload_to='media/favicon/', verbose_name='title icon'),
        ),
    ]
